development:
  ExportProcessor:
    cron: "*/1 * * * *"
    queue: normal

  UpdateImportProcessor:
    cron: "*/2 * * * *"
    queue: normal

  Lsi::LsiSimulator:
    cron: "*/3 * * * *"
    queue: normal
production:
  ExportProcessor:
    cron: "0 * * * *"
    queue: normal

  UpdateImportProcessor:
    cron: "30 * * * *"
    queue: normal
