development:
  ExportProcessor:
    cron: "0,10,20,30,40,50 * * * *"
    queue: normal

  UpdateImportProcessor:
    cron: "2,12,22,32,42,52 * * * *"
    queue: normal

  Lsi::LsiSimulator:
    cron: "3,13,23,33,43,53 * * * *"
    queue: normal
production:
  ExportProcessor:
    cron: "0 * * * *"
    queue: normal

  UpdateImportProcessor:
    cron: "30 * * * *"
    queue: normal
